unique_ids:
  forms: {SignUpDialog: QLX276KUPL6CQ472UBX47QU7DMSRJFNQ, WelcomePage: E746Y72XYPM2AJUE5IYVR2ORXDGXDTIN,
    sign_in: YLCUTPZMIUVEY2PMAPHFQ5QU362LF7NF}
  modules: {AuthFlow: TRANI3WVUTIBZOMXMKA4A6MYFHC4G65L, Main: QYNCKINR2XBFSMOYGAQMQCI7GA7QB44J}
  server_modules: {Authentication: N45CRDBKWKK6FWVDD5FHIXLW7MNIDB55, Authentication.SignIn: OUL553ODRRYI7LMJY3ZM3JQIZX2L6SH2,
    Authentication.SignUp: 3TG4I7UJPFFHEO2T4FILZINK5N3MRFZ4}
  assets: {harold.jpg: NIR7CZW3GF4BSCHLJ3BM742SP5JJUFVB, standard-page.html: WBQ4Y35HQOOLKOC6SROHAIF4N5DZ4K2Q,
    theme.css: QS6E3PLQXCMQFUUQLR7YVYHQ6FISJG4T, triangle.png: EONLCBECP33IYJ675JTPWGM3JL2MYO6A}
