unique_ids:
  forms: {sign_up: O5GULNRCQQZH6APB7CNPYPINUNLEGIMC, welcome_page: V6CVY72VNLEWP33IS32FYTMKIEYNVUNB}
  modules: {}
  server_modules: {Authentication: N45CRDBKWKK6FWVDD5FHIXLW7MNIDB55, Authentication.SignIn: OUL553ODRRYI7LMJY3ZM3JQIZX2L6SH2,
    Authentication.SignUp: 3TG4I7UJPFFHEO2T4FILZINK5N3MRFZ4}
  assets: {standard-page.html: WBQ4Y35HQOOLKOC6SROHAIF4N5DZ4K2Q, theme.css: QS6E3PLQXCMQFUUQLR7YVYHQ6FISJG4T}
