unique_ids:
  forms: {Authentication: O5GULNRCQQZH6APB7CNPYPINUNLEGIMC}
  modules: {}
  server_modules: {ServerModule1: Z3BGK3624PZRNU4S235CEG2IPJE2DOMP}
  assets: {standard-page.html: WBQ4Y35HQOOLKOC6SROHAIF4N5DZ4K2Q, theme.css: QS6E3PLQXCMQFUUQLR7YVYHQ6FISJG4T}
