unique_ids:
  forms: {StudentHomePage: IIIDAREJ3VLTUXKFGL5NTTIGA475UONH, sign_in: YLCUTPZMIUVEY2PMAPHFQ5QU362LF7NF,
    PasswordResetDialog: VZJYGMMC6UQJNJT572BGUQT4SZGOIHXN, BankHomePage: BYIOFQHTIPZKPQE2GU7I3AH3OOJ7QUO2,
    ForgottenPasswordDialog: CMTDAH2O6Z45CW7NYSPUSZ64GOBASQJD, RegistrarHomePage: JRQOSEQ7OYC2TPPWCBRAW6Y7PWT7QBMQ,
    SignUpDialog: QLX276KUPL6CQ472UBX47QU7DMSRJFNQ, WelcomePage: E746Y72XYPM2AJUE5IYVR2ORXDGXDTIN}
  modules: {Main: QYNCKINR2XBFSMOYGAQMQCI7GA7QB44J, AuthFlow: TRANI3WVUTIBZOMXMKA4A6MYFHC4G65L}
  server_modules: {Authenticator: UEPQFL46CAVDOD6LD6265K524EPIKOQG}
  assets: {doge.png: D5YKOFW4RTVTNAF2F6MCM2LOFCIIMM7X, harold.jpg: NIR7CZW3GF4BSCHLJ3BM742SP5JJUFVB,
    standard-page.html: WBQ4Y35HQOOLKOC6SROHAIF4N5DZ4K2Q, theme.css: QS6E3PLQXCMQFUUQLR7YVYHQ6FISJG4T,
    triangle.png: EONLCBECP33IYJ675JTPWGM3JL2MYO6A}
