unique_ids:
  forms: {sign_up: O5GULNRCQQZH6APB7CNPYPINUNLEGIMC}
  modules: {}
  server_modules: {AuthenticationModule: Z3BGK3624PZRNU4S235CEG2IPJE2DOMP, ServerModule2: B2PIS4YJR5Z3UOA5XAH26FHKX5MOTEZJ}
  assets: {standard-page.html: WBQ4Y35HQOOLKOC6SROHAIF4N5DZ4K2Q, theme.css: QS6E3PLQXCMQFUUQLR7YVYHQ6FISJG4T}
